### PR TITLE
Added support for lists and arrays of nested objects

### PR DESCRIPTION
**Pull request by dguisinger**

### CODE REVIEW

**Comment by scale-tone** [comment]
Then, why not just using a simple generic converter like this:

    class DynamoDbListConverter<TElement> : IPropertyConverter
    {
        public DynamoDBEntry ToEntry(object value)
        {
            var result = new DynamoDBList();
            foreach (var element in (IEnumerable) value)
            {
                result.Add(DynamoDbConversionUtils.ToDocumentConverter(typeof(TElement))(element));
            }
            return result;
        }

        public object FromEntry(DynamoDBEntry entry)
        {
            var dynamoDbList = entry as DynamoDBList;
            if (dynamoDbList == null)
            {
                return null;
            }

            var result = (IList)Activator.CreateInstance(typeof(List<>).MakeGenericType(typeof(TElement)));
            foreach (var doc in dynamoDbList.Entries.Select(e => e as Document).Where(d => d != null))
            {
                result.Add(doc.ToObject(typeof (TElement)));
            }
            return result;
        }
    }

And then:

        [DynamoDBProperty(typeof(DynamoDbListConverter<EntityPermissions>))]
        public List<EntityPermissions> Permissions { get; set; } 

?

This would enable both read and write operations and doesn't require making those deep code changes...

**Comment by dguisinger** [comment]
I wouldn't consider that to be "deep" changes, its calling your deserializer recursively when it hits lists of elements.  Its only about 15 lines and most of the code is just detecting the type of the deserialization target list/array.  At first I thought the problem was an AWS SDK issue, but after discussing it with the guys at AWS it ends up Document no longer needs converters, it deserializes automatically.

The solution in the pull doesn't require tagging each property and acts the way one would expect coming from the SDK.  It also doesn't require the application to have code that is aware of the AWS Document object which you are trying to move away from (its used internally, but a full migration away from Document in Linq2DynamoDB wouldn't create code changes on the application side where the converter relies on the existence of Document)

The code works for all data I've attempted to read, and the changes only impact arrays and lists.
If you are concerned about writing data, I can work on that this week.  It was my plan to submit patches for that (if needed).

**Comment by scale-tone** [comment]
Yes, in fact, I am concerned about writing fields of those types. If you implement that, it would be great.

And may I also ask you to fix some things in your code:
1) Please, use "as" followed by check for null instead of "is" followed by "as" - this is a known best practice for C#, because it's faster.
2) Please, use Primitive.ToObject() instead of GetFromPrimitiveConversionFunctor(). This is a) faster (the functor is memoized in the first case) and b) tolerant to nulls.
3) A code style thing: please, use "var" instead of type names whenever possible.

Thank you for your help.

**Comment by dguisinger** [comment]
Alright, I will make those changes and work on the field writing.

**Comment by dguisinger** [comment]
I submitted the write code fixed the styling of the read code yesterday.  I also added support for reading and writing a POCO object if its a property of an entity instead of an array or list.

**Pull request merged**
